# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '张尊云day14网易新闻' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 张尊云day14网易新闻

pod 'AFNetworking'
pod 'SDWebImage'
pod 'Masonry'
pod 'FMDB'
pod 'YYModel'

  target '张尊云day14网易新闻Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
